excluded:
 - MedevioGraphQL/Sources/MedevioGraphQL/Generated
 - MedevioGraphQL/Sources/MedevioGraphQLFixtures/Generated
 - MedevioGraphQL/.build
only_rules:
 - array_init
 - capture_variable
 - closing_brace
 - closure_parameter_position
 - closure_spacing
 - collection_alignment
 - colon
 - comma
 - comma_inheritance
 - comment_spacing
 - compiler_protocol_init
 - computed_accessors_order
 - contains_over_filter_count
 - contains_over_filter_is_empty
 - contains_over_first_not_nil
 - contains_over_range_nil_comparison
 - control_statement
 - convenience_type
 - deployment_target
 - discarded_notification_center_observer
 - discouraged_assert
 - discouraged_direct_init
 - discouraged_none_name
 - discouraged_object_literal
 - duplicate_imports
 - duplicated_key_in_dictionary_literal
 - empty_collection_literal
 - empty_count
 - empty_enum_arguments
 - empty_parameters
 - empty_parentheses_with_trailing_closure
 - empty_string
 - empty_xctest_method
 - expiring_todo
 - explicit_init
 - explicit_self
 - extension_access_modifier
 - file_header
 - file_name_no_space
 - first_where
 - flatmap_over_map_reduce
 - for_where
 - ibinspectable_in_extension
 - identical_operands
 - implicit_getter
 - implicit_return
 - indentation_width
 - joined_default_parameter
 - last_where
 - leading_whitespace
 - legacy_multiple
 - legacy_objc_type
 - literal_expression_end_indentation
 - local_doc_comment
 - lower_acl_than_parent
 - modifier_order
 - multiline_arguments_brackets
 - multiline_function_chains
 - multiline_literal_brackets
 - multiline_parameters
 - multiline_parameters_brackets
 - no_space_in_method_call
 - object_literal
 - operator_usage_whitespace
 - operator_whitespace
 - optional_enum_case_matching
 - overridden_super_call
 - override_in_extension
 - prefer_self_in_static_references
 - prefer_self_type_over_type_of_self
 - prefer_zero_over_explicit_init
 - prohibited_interface_builder
 - prohibited_super_call
 - protocol_property_accessors_order
 - raw_value_for_camel_cased_codable_enum
 - reduce_into
 - redundant_nil_coalescing
 - redundant_optional_initialization
 - redundant_set_access_control
 - redundant_string_enum_value
 - redundant_type_annotation
 - redundant_void_return
 - required_enum_case
 - return_arrow_whitespace
 - return_value_from_void_function
 - self_binding
 - shorthand_operator
 - shorthand_optional_binding
 - single_test_class
 - sorted_first_last
 - sorted_imports
 - statement_position
 - static_operator
 - strong_iboutlet
 - switch_case_alignment
 - switch_case_on_newline
 - syntactic_sugar
 - test_case_accessibility
 - toggle_bool
 - trailing_closure
 - trailing_newline
 - trailing_semicolon
 - trailing_whitespace
 - typesafe_array_init
 - unavailable_function
 - unneeded_break_in_switch
 - unneeded_parentheses_in_closure_argument
 - unused_capture_list
 - unused_declaration
 - unused_import
 - unused_setter_value
 - vertical_whitespace_opening_braces
 - void_return
 - xct_specific_matcher
